### ISSUE TITLE
Решить проблему почему не отправляются запросы на сервак

### ISSUE THREAD

**Issue by Jho00** [NesQ1kx/lets-discuss#6]
У нас есть боевой сервер (165.22.84.45)
Надо сделать так, чтобы приложение к нему запросы слало по сети интернет

**Comment by Jho00** [comment]
Я пока сервак с DO отключил, надо просто что-то сфетчить

**Comment by NesQ1kx** [comment]
Мб удалить таску? Решено же

**Comment by Jho00** [comment]
> Мб удалить таску? Решено же

Удаляю, ток добавь промблемные моменты в issue, то, что сейчас надо сделать
